def renomear_colunas(df):
    df = df.rename(columns={
        "Submission ID": "ID_JOTFORM",
        
        "Submission Date": "DATA_JOTFORM",
        "Geolocation": "GEOLOCATION",
        "ID": "ID_INTERNO",
        "Funcionário Cadastro": "FUNCIONARIO",
        "Ocorrência De Campo Cadastro": "ACEITE_CADASTRO",
        "Aceita Fazer O Cadastro De Esgoto": "ACEITE_ESGOTO",
        "Data Cadastro": "DATA_CADASTRO",
        "Município": "MUNICIPIO",
        "Núcleo De Atuação": "NUCLEO",
        "Endereço": "ENDERECO",
        "Número": "NUMERO",
        "Complemento": "COMPLEMENTO",
        "Bairro": "BAIRRO",
        "Cep": "CEP",
        "Foto Imóvel": "FOTO_IMOVEL",
        "Situação Do Imóvel": "SITUACAO_IMOVEL",
        "Imóvel": "IMOVEL",
        "Nome": "NOME",
        "Data Nasc": "DATA_NASCIMENTO",
        "Caixa U.M.A. Existente": "TEM_CAIXA",
        "Cpf": "CPF",
        "Foto Verso Cpf": "FOTO_CPF",
        "Rg": "RG",
        "Foto Frente RG": "FOTO_RG_FRENTE",
        "Foto Verso RG": "FOTO_RG_VERSO",
        "Escolaridade": "ESCOLARIDADE",
        "Email": "EMAIL",
        "Telefone": "TELEFONE",
        "Você Tem Cadastro No Cad Único": "TEM_CADUNICO",
        "Sexo": "SEXO",
        "Imóvel Reside PCD": "TEM_PCD",
        "Qual": "TIPO_PCD",
        "Quantas": "QTD_PCD",
        "Nº Adultos": "QTD_ADULTO",
        "Nº De Crianças": "QTD_CRIANCA",
        "Quantos Trabalham": "QTD_TRABALHA",
        "Renda Familiar (Salário Mínimo)": "RENDA",
        "Família chefiada por mulher:": "CHEFIADA_MULHER",
        "Imóvel possui Caixa d 'água": "TEM_CAIXA_DAGUA",
        "Imóvel permitido instalação de caixa d'água": "IMV_PER_CX_DGA",
        "Existe histórico de doenças de veiculação hídrica": "HIS_DOE_VEI_HID",
        "Você e": "VOCE_E",
        "Tipos de Pavimento:": "TP_PAVIMENTO",
        "Tipo de Passeio:": "TP_PASSEIO",
        "Tipo de serviço": "TP_SERVICO",
        "Ligação": "LIGACAO",
        "Pde": "PDE",
        "Residência Com Hidrômetro": "RESID_HIDRO",
        "Número Do Hidrômetro": "NUM_HIDRO",
        "Leitura Hidrômetro": "LEITURA_HD",
        "Foto Do Hidrômetro": "FOTO_HD",
        "Objetivo E Os Benefícios Que Você Espera Com A Chegada Do Programa Água Legal Da Sabesp Em Sua Comunidade": "CHEG_PRG_SABESP",
        "A Família Recebe Benefício Social Do Governo? Caso Seja Recebido, Qual É O Benefício? Ex: Bolsa Família, Leve Leite, Gás Entre Outros.": "REC_BENE_GOV",
        "Caso Receba, Qual É O Benefício? Ex: Bolsa Família, Leve Leite, Gás Entre Outros.": "QUAL_BENEFICIO",
        "Na Família Possui Pessoa Com Deficiência (PCD) No Imóvel? Caso Tenha, Qual A Deficiência?": "PCD_NO_IMOVEL",
        "No Imóvel Existe Pessoa Idosa (Acima De 60 Anos)": "IDOSA_IMOVEL",
        "A Família Depende Da Renda Do Idoso?": "DEPENDE_IDOSO",
        "Aceita Participar Das Ações E Atividades Oferecidas Pelo Programa?": "PART_ATV_PGM",
        "Existe Alguém No Imóvel Que Faz Tratamento Contínuo Na Rede SUS?": "TRT_CONT_SUS",
        "O Tratamento É Para Qual Doença?": "TRT_QUAL_DOENCA",
        "Observação": "OBS",
        "Assinatura Digital": "ASS_DIGITAL",
        "Assinatura Colaborador": "ASS_COLABORADOR",
        "DATA INSTALAÇÃO CAIXA UMA": "DT_INST_CX_UMA",
        "OCORRÊNCIA DE CAMPO CAIXA UMA": "OCO_CAMP_CX_UMA",
        "FUNCIONÁRIO  CAIXA UMA": "FUN_CX_UMA",
        "FOTO ANTES DO SERVIÇO": "FOTO_ANTES_SERV",
        "FOTO DURANTE O SERVIÇO": "FOTO_DUR_SERV",
        "FOTO DO SERVIÇO EXECUTADO .": "FOTO_SERV_EXE",
        "CAIXA JÁ INSTALADA NO IMOVEL": "CX_INST_IMOVEL",
        "CAIXA UMA": "CAIXA_UMA",
        "MATERIAL >> BLOCO BAIANO	 >> QT": "MAT_BL_BAIAN_QT",
        "MATERIAL >> BLOCO BAIANO	 >> METRO": "MAT_BL_BAIAN_MT",
        "MATERIAL >> BLOCO BAIANO	 >> LATA": "MAT_BL_BAIAN_LT",
        "MATERIAL >> CAIXA UMA	 >> QT": "MAT_CX_UMA_QT",
        "MATERIAL >> CAIXA UMA	 >> METRO": "MAT_CX_UMA_MT",
        "MATERIAL >> CAIXA UMA	 >> LATA": "MAT_CX_UMA_LT",
        "MATERIAL >> PEDRA	 >> QT": "MAT_PD_BAIAN_QT",
        "MATERIAL >> PEDRA	 >> METRO": "MAT_PD_BAIAN_MT",
        "MATERIAL >> PEDRA	 >> LATA": "MAT_PD_BAIAN_LT",
        "MATERIAL >> CIMENTO PA	 >> QT": "MAT_CIMEN_PA_QT",
        "MATERIAL >> CIMENTO PA	 >> METRO": "MAT_CIMEN_PA_MT",
        "MATERIAL >> CIMENTO PA	 >> LATA": "MAT_CIMEN_PA_LT",
        "MATERIAL >> AREIA LATA	 >> QT": "MAT_AREIA_LT_QT",
        "MATERIAL >> AREIA LATA	 >> METRO": "MAT_AREIA_LT_MT",
        "MATERIAL >> AREIA LATA	 >> LATA": "MAT_AREIA_LT_LT",
        "MATERIAL >> TIJOLO COMUM >> QT": "MAT_TIJ_COMU_QT",
        "MATERIAL >> TIJOLO COMUM >> METRO": "MAT_TIJ_COMU_MT",
        "MATERIAL >> TIJOLO COMUM >> LATA": "MAT_TIJ_COMU_LT",
        "OBSERVAÇÃO ...": "OBS_1",
        "Colaborador ..": "COLABORADOR_1",
        "DATA LIGACAO EXECUTADA": "DAT_LIGACAO_EXE",
        "OCORRÊNCIA DE CAMPO LIGAÇÃO": "OCOR_CAMPO_LIG",
        "FUNCIONÁRIO LIGAÇÃO": "FUN_LIGACAO",
        "FOTO DO ANTES DO SERVIÇO": "FOT_ANTES_SERV1",
        "FOTO DURANTE O SERVIÇO .": "FOTO_DUR_SERV1",
        "FOTO DO LACRE DO HIDRO ..": "FOTO_LACRE_HD",
        "FOTO DO SERVIÇO EXECUTADO ....": "FOTO_SERV_EXE1",
        "HIDRO NOVO QR": "HD_NOVO_QR",
        "HIDRO NOVO": "HD_NOVO",
        "Numero de Cordoalha": "NUM_CODOALHO",
        "ÁREA DE ATUAÇÃO": "AREA_ATUACAO",
        "NÚMERO DO FORNECIMENTO": "NUM_FORNECIMENT",
        "INSTALAÇÃO": "INSTALACAO",
        "JA TEM  INSTALAÇÃO NO LOCAL": "JA_INST_LOCAL",
        "NÚMERO DO HIDRO NO IMOVEL": "NUM_HD_IMOVEL",
        "Complemento do Hidro": "COMPLEMENTO_HD",
        "A Ligação Precisa de Reposição?": "LIG_PRECISA_REP",
        "Reposição >> CIMENTADO >> METRAGEM": "REP_CIM_MT",
        "Reposição >> CIMENTADO >> REPOSIÇÃO EXECUTADA": "REP_CIM_REP_EXE",
        "Reposição >> PISO ESPECIAL >> METRAGEM": "REP_PISO_ESP_MT",
        "Reposição >> PISO ESPECIAL >> REPOSIÇÃO EXECUTADA": "REP_PISO_REP_EX",
        "Reposição >> ASFALTO >> METRAGEM": "REP_ASF_MT",
        "Reposição >> ASFALTO >> REPOSIÇÃO EXECUTADA": "REP_ASF_REP_EXE",
        "MATERIAIS >> PAD DE 20	 >> QT": "MAT_PAD_20_QT",
        "MATERIAIS >> PAD DE 20	 >> METRO": "MAT_PAD_20_MT",
        "MATERIAIS >> PAD DE 20	 >> LATA": "MAT_PAD_20_LT",
        "MATERIAIS >> PAD DE 32	 >> QT": "MAT_PAD_32_QT",
        "MATERIAIS >> PAD DE 32	 >> METRO": "MAT_PAD_32_MT",
        "MATERIAIS >> PAD DE 32	 >> LATA": "MAT_PAD_32_LT",
        "MATERIAIS >> KIT SIMPES	 >> QT": "MAT_KIT_SIMP_QT",
        "MATERIAIS >> KIT SIMPES	 >> METRO": "MAT_KIT_SIMP_MT",
        "MATERIAIS >> KIT SIMPES	 >> LATA": "MAT_KIT_SIMP_LT",
        "MATERIAIS >> HIDROMETRO >> QT": "MAT_HIDRO_QT",
        "MATERIAIS >> HIDROMETRO >> METRO": "MAT_HIDRO_MT",
        "MATERIAIS >> HIDROMETRO >> LATA": "MAT_HIDRO_LT",
        "MATERIAIS >> LACRE >> QT": "MAT_LACRE_QT",
        "MATERIAIS >> LACRE >> METRO": "MAT_LACRE_MT",
        "MATERIAIS >> LACRE >> LATA": "MAT_LACRE_LT",
        "MATERIAIS >> UNIÃO DE 20	 >> QT": "MAT_UNIAO_20_QT",
        "MATERIAIS >> UNIÃO DE 20	 >> METRO": "MAT_UNIAO_20_MT",
        "MATERIAIS >> UNIÃO DE 20	 >> LATA": "MAT_UNIAO_20_LT",
        "MATERIAIS >> T DE SERVIÇO DE 32X20 MM >> QT": "T_SERV_32X20_QT",
        "MATERIAIS >> T DE SERVIÇO DE 32X20 MM >> METRO": "T_SERV_32X20_MT",
        "MATERIAIS >> T DE SERVIÇO DE 32X20 MM >> LATA": "T_SERV_32X20_LT",
        "MATERIAIS >> T DE SERVIÇO DE 75X20 MM >> QT": "T_SERV_75X20_QT",
        "MATERIAIS >> T DE SERVIÇO DE 75X20 MM >> METRO": "T_SERV_75X20_MT",
        "MATERIAIS >> T DE SERVIÇO DE 75X20 MM >> LATA": "T_SERV_75X20_LT",
        "MATERIAIS >> T DE SERVIÇO DE 100X20 MM	 >> QT": "T_SERV100X20_QT",
        "MATERIAIS >> T DE SERVIÇO DE 100X20 MM	 >> METRO": "T_SERV100X20_MT",
        "MATERIAIS >> T DE SERVIÇO DE 100X20 MM	 >> LATA": "T_SERV100X20_LT",
        "MATERIAIS >> ADAP MARRON MACHO C/R	 >> QT": "ADP_MAR_M_CR_QT",
        "MATERIAIS >> ADAP MARRON MACHO C/R	 >> METRO": "ADP_MAR_M_CR_MT",
        "MATERIAIS >> ADAP MARRON MACHO C/R	 >> LATA": "ADP_MAR_M_CR_LT",
        "MATERIAIS >> ADAP MARRON FEMEA C / R	 >> QT": "ADP_MAR_F_CR_QT",
        "MATERIAIS >> ADAP MARRON FEMEA C / R	 >> METRO": "ADP_MAR_F_CR_MT",
        "MATERIAIS >> ADAP MARRON FEMEA C / R	 >> LATA": "ADP_MAR_F_CR_LT",
        "MATERIAIS >> ADAP METAL	ADAP PRETO >> QT": "ADP_META_PT_QT",
        "MATERIAIS >> ADAP METAL	ADAP PRETO >> METRO": "ADP_META_PT_MT",
        "MATERIAIS >> ADAP METAL	ADAP PRETO >> LATA": "ADP_META_PT_LT",
        "MATERIAIS >> COTOVELO DE 3/4 MARRON COLA	 >> QT": "COT_34_MAR_C_QT",
        "MATERIAIS >> COTOVELO DE 3/4 MARRON COLA	 >> METRO": "COT_34_MAR_C_MT",
        "MATERIAIS >> COTOVELO DE 3/4 MARRON COLA	 >> LATA": "COT_34_MAR_C_LT",
        "MATERIAIS >> COTOVELO DE 3/4 BRANCO ROSCA	 >> QT": "COT_34_BRC_R_QT",
        "MATERIAIS >> COTOVELO DE 3/4 BRANCO ROSCA	 >> METRO": "COT_34_BRC_R_MT",
        "MATERIAIS >> COTOVELO DE 3/4 BRANCO ROSCA	 >> LATA": "COT_34_BRC_R_LT",
        "MATERIAIS >> T 3/4 MARRON COLA			 >> QT": "T_34_MARRO_C_QT",
        "MATERIAIS >> T 3/4 MARRON COLA			 >> METRO": "T_34_MARRO_C_MT",
        "MATERIAIS >> T 3/4 MARRON COLA			 >> LATA": "T_34_MARRO_C_LT",
        "MATERIAIS >> CAP 32	 >> QT": "MAT_CAP_32_QT",
        "MATERIAIS >> CAP 32	 >> METRO": "MAT_CAP_32_MT",
        "MATERIAIS >> CAP 32	 >> LATA": "MAT_CAP_32_LT",
        "MATERIAIS >> T DE ELETROFUSAO 32X20 MM >> QT": "T_ELETF32X2O_QT",
        "MATERIAIS >> T DE ELETROFUSAO 32X20 MM >> METRO": "T_ELETF32X2O_MT",
        "MATERIAIS >> T DE ELETROFUSAO 32X20 MM >> LATA": "T_ELETF32X2O_LT",
        "MATERIAIS >> T DE ELETROFUSAO  63X20 MM >> QT": "T_ELETF63X2O_QT",
        "MATERIAIS >> T DE ELETROFUSAO  63X20 MM >> METRO": "T_ELETF63X2O_MT",
        "MATERIAIS >> T DE ELETROFUSAO  63X20 MM >> LATA": "T_ELETF63X2O_LT",
        "MATERIAIS >> T DE ELETROFUSAO  90X20 MM >> QT": "T_ELETF90X2O_QT",
        "MATERIAIS >> T DE ELETROFUSAO  90X20 MM >> METRO": "T_ELETF90X2O_MT",
        "MATERIAIS >> T DE ELETROFUSAO  90X20 MM >> LATA": "T_ELETF90X2O_LT",
        "MATERIAIS >> LUVA DE ELETROFUSAO DE 20 MM >> QT": "LV_ELETF2OMM_QT",
        "MATERIAIS >> LUVA DE ELETROFUSAO DE 20 MM >> METRO": "LV_ELETF2OMM_MT",
        "MATERIAIS >> LUVA DE ELETROFUSAO DE 20 MM >> LATA": "LV_ELETF2OMM_LT",
        "MATERIAIS >> LUVA DE ELETROFUSAO DE 32 MM >> QT": "LV_ELETF32MM_QT",
        "MATERIAIS >> LUVA DE ELETROFUSAO DE 32 MM >> METRO": "LV_ELETF32MM_MT",
        "MATERIAIS >> LUVA DE ELETROFUSAO DE 32 MM >> LATA": "LV_ELETF32MM_LT",
        "MATERIAIS >> CINTA TOMADA 50X150 >> QT": "CT_TOM50X150_QT",
        "MATERIAIS >> CINTA TOMADA 50X150 >> METRO": "CT_TOM50X150_MT",
        "MATERIAIS >> CINTA TOMADA 50X150 >> LATA": "CT_TOM50X150_LT",
        "MATERIAIS >> COTOVELO ACOPLADO 20 MM >> QT": "COT_ACPL20MM_QT",
        "MATERIAIS >> COTOVELO ACOPLADO 20 MM >> METRO": "COT_ACPL20MM_MT",
        "MATERIAIS >> COTOVELO ACOPLADO 20 MM >> LATA": "COT_ACPL20MM_LT",
        "MATERIAIS >> COTOVELO ACOPLADO 32 MM >> QT": "COT_ACPL32MM_QT",
        "MATERIAIS >> COTOVELO ACOPLADO 32 MM >> METRO": "COT_ACPL32MM_MT",
        "MATERIAIS >> COTOVELO ACOPLADO 32 MM >> LATA": "COT_ACPL32MM_LT",
        "MATERIAIS >> T DE ELETROFUSAO 110X20 MM >> QT": "T_ELEF110X2O_QT",
        "MATERIAIS >> T DE ELETROFUSAO 110X20 MM >> METRO": "T_ELEF110X2O_MT",
        "MATERIAIS >> T DE ELETROFUSAO 110X20 MM >> LATA": "T_ELEF110X2O_LT",
        "MATERIAIS >> T DE ELETROFUSAO 160X20 MM >> QT": "T_ELEF160X2O_QT",
        "MATERIAIS >> T DE ELETROFUSAO 160X20 MM >> METRO": "T_ELEF160X2O_MT",
        "MATERIAIS >> T DE ELETROFUSAO 160X20 MM >> LATA": "T_ELEF160X2O_LT",
        "OBSERVAÇÃO.........": "OBS_2",
        "Colaborador......": "COLABORADOR_2",
        "Data Ligação De Esgoto": "DATA_LIG_ESG",
        "Nome Da Equipe": "NOME_DA_EQP",
        "Ocorrência De Ligação De Esgoto": "OCORRÊNCIA_DE_ESG",
        "Foto Antes": "FOTO_ANTES",
        "Foto Depois": "FOTO_DEPOIS",
        "Tipos De Pavimento": "TIPOS_DE_PAV",
        "Tipos De Passeio": "TIPOS_DE_PASS",
        "Posição Legal Da Ligação": "POSIÇÃO_LEG_LIG",
        "Lacre Cordoalho: >> NOVO >> <span style=\"color: rgb(44, 51, 69); font-family: Inter, san...": "LACRE_COR_NOVO",
        "Lacre Cordoalho: >> ANTIGO >> <span style=\"color: rgb(44, 51, 69); font-family: Inter, san...": "LACRE_COR_ANTIG",
        "Lacre Cordoalho": "LACRE_CORDOALHO",
        "Reposição": "REPOSICAO",
        "Metros": "METROS",
        "Material >> CURVA 90° 100 MM >> Insatisfeito(a)": "CUR_90G_100MM_I",
        "Material >> CURVA 90° 100 MM >> Pouco Satisfeito(a)": "CUR_90G_100MM_P",
        "Material >> CURVA 90° 150 MM >> Insatisfeito(a)": "CUR_90G_150MM_I",
        "Material >> CURVA 90° 150 MM >> Pouco Satisfeito(a)": "CUR_90G_150MM_P",
        "Material >> CURVA 90° 200 MM >> Insatisfeito(a)": "CUR_90G_200MM_I",
        "Material >> CURVA 90° 200 MM >> Pouco Satisfeito(a)": "CUR_90G_200MM_P",
        "Material >> CURVA 45° 100 MM >> Insatisfeito(a)": "CUR_45G_100MM_I",
        "Material >> CURVA 45° 100 MM >> Pouco Satisfeito(a)": "CUR_45G_100MM_P",
        "Material >> CURVA 45° 150 MM >> Insatisfeito(a)": "CUR_45G_150MM_I",
        "Material >> CURVA 45° 150 MM >> Pouco Satisfeito(a)": "CUR_45G_150MM_P",
        "Material >> CURVA 45° 200 MM >> Insatisfeito(a)": "CUR_45G_200MM_I",
        "Material >> CURVA 45° 200 MM >> Pouco Satisfeito(a)": "CUR_45G_200MM_P",
        "Material >> CELIN 150 >> Insatisfeito(a)": "CELIN_150_INSA",
        "Material >> CELIN 150 >> Pouco Satisfeito(a)": "CELIN_150_PSAT",
        "Material >> CELIN  200 >> Insatisfeito(a)": "CELIN_200_INSA",
        "Material >> CELIN  200 >> Pouco Satisfeito(a)": "CELIN_200_PSAT",
        "Material >> T PVC MARRON 75 >> Insatisfeito(a)": "T_PVT_MAR_75_IN",
        "Material >> T PVC MARRON 75 >> Pouco Satisfeito(a)": "T_PVT_MAR_75_PS",
        "Material >> T PVC MARRON 100 >> Insatisfeito(a)": "T_PVT_MAR_100_I",
        "Material >> T PVC MARRON 100 >> Pouco Satisfeito(a)": "T_PVT_MAR_100_P",
        "Material >> LUVA PVC MARRON 100 >> Insatisfeito(a)": "LV_PVC_MA_100_I",
        "Material >> LUVA PVC MARRON 100 >> Pouco Satisfeito(a)": "LV_PVC_MA_100_P",
        "Material >> TUBO PVC MARRON 100 >> Insatisfeito(a)": "TB_PVC_MA_100_I",
        "Material >> TUBO PVC MARRON 100 >> Pouco Satisfeito(a)": "TB_PVC_MA_100_P",
        "Material >> ESTRONCA DE VIGA P/ ESCORAMENT >> Insatisfeito(a)": "ESTC_VG_ECRMT_I",
        "Material >> ESTRONCA DE VIGA P/ ESCORAMENT >> Pouco Satisfeito(a)": "ESTC_VG_ECRMT_P",
        "Obs": "OBS_3",
        "Tags": "TAGS_3",
        "01Colaborador Caixa Uma": "COLAB_CAIXA_UMA",
        "COLABORADOR": "COLABORADOR_3",
        "IP":"IP",
        "No Label":"NO_LABEL"
    })
    return df
